<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net20</TargetFramework>
    <RootNamespace>RosuPP</RootNamespace>
    <TieredPGO>true</TieredPGO>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Optimize>true</Optimize>
    <LangVersion>13</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
</Project>
